### ISSUE TITLE
ModuleNotFoundError: No module named 'model_management'

### ISSUE THREAD

**Issue by gkiryaziev** [mav-rik/facerestore_cf#17]
After this commit https://github.com/comfyanonymous/ComfyUI/commit/0c55f16c9e66eaa4915e288b34e4f848fb2d949f the error **ModuleNotFoundError: No module named 'model_management'** appeared.

To solve it, you need to change in **`custom_nodes\facerestore_cf\__init__.py`** in the second line:

**`import model_management`**
to
**`from comfy import model_management`**

**Comment by mav-rik** [comment]
@gkiryaziev don't you mind to submit a PR with the described fix?

**Comment by gkiryaziev** [comment]
Issue fixed

**Comment by gkiryaziev** [comment]
Issue fixed
